/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.Date;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Locale;
import java.util.Formatter;
import javax.swing.JOptionPane;
import reports.reporte_caja;
import reports.reporte_paciente;

/**
 *
 * @author Informatica
 */
public class frmReportes extends javax.swing.JInternalFrame {
    
    private String fecha_inicial;
    private String fecha_final;

    /**
     * Creates new form frmReportes
     */
    public frmReportes() {
        initComponents();
        lblfecha_inicial.setEnabled(false);
        lblfecha_final.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtReportes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dcofecha_final = new com.toedter.calendar.JDateChooser();
        dcofecha_inicial = new com.toedter.calendar.JDateChooser();
        lblfecha_inicial = new javax.swing.JLabel();
        lblfecha_final = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtInformeMedico = new javax.swing.JRadioButton();
        rbtFarmacia = new javax.swing.JRadioButton();
        rbtCertificadoSalud = new javax.swing.JRadioButton();
        rbtCaja = new javax.swing.JRadioButton();
        rbtPaciente = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte");

        jPanel1.setBackground(new java.awt.Color(78, 150, 203));

        jLabel1.setText("DE");

        jLabel2.setText("HASTA");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/reporte_2.png"))); // NOI18N
        jButton1.setText("PROCESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("REPORTES GENERALES");

        dcofecha_final.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcofecha_finalPropertyChange(evt);
            }
        });

        dcofecha_inicial.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcofecha_inicialPropertyChange(evt);
            }
        });

        lblfecha_inicial.setBorder(new javax.swing.border.MatteBorder(null));

        lblfecha_final.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel2.setBackground(new java.awt.Color(78, 150, 203));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Modulos:"));

        rbtReportes.add(rbtInformeMedico);
        rbtInformeMedico.setText("Informe medico");

        rbtReportes.add(rbtFarmacia);
        rbtFarmacia.setText("Farmacia");
        rbtFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFarmaciaActionPerformed(evt);
            }
        });

        rbtReportes.add(rbtCertificadoSalud);
        rbtCertificadoSalud.setText("Certificado de Salud");

        rbtReportes.add(rbtCaja);
        rbtCaja.setText("Caja");

        rbtReportes.add(rbtPaciente);
        rbtPaciente.setText("Paciente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtInformeMedico)
                    .addComponent(rbtFarmacia)
                    .addComponent(rbtCaja)
                    .addComponent(rbtCertificadoSalud)
                    .addComponent(rbtPaciente))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rbtPaciente)
                .addGap(18, 18, 18)
                .addComponent(rbtCertificadoSalud)
                .addGap(18, 18, 18)
                .addComponent(rbtCaja)
                .addGap(18, 18, 18)
                .addComponent(rbtFarmacia)
                .addGap(18, 18, 18)
                .addComponent(rbtInformeMedico)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dcofecha_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addComponent(dcofecha_final, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2))
                                .addGap(73, 73, 73))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcofecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcofecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblfecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblfecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (lblfecha_inicial.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "INGRESE FECHA INICIAL");
            lblfecha_inicial.requestFocus();
            return;
        }
        if (lblfecha_final.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "INGRESE FECHA FINAL");
            lblfecha_final.requestFocus();
            return;
        }
        
        fecha_inicial = lblfecha_inicial.getText();
        fecha_final = lblfecha_final.getText();
        
        if (rbtCaja.isSelected()) {
            reporte_caja reporte = new reporte_caja();
            reporte.reporteCajaPorFechas(fecha_inicial, fecha_final);
            
        } else if (rbtCertificadoSalud.isSelected()) {
            
        } else if (rbtFarmacia.isSelected()) {
            
        } else if (rbtInformeMedico.isSelected()) {
            
        } else if (rbtPaciente.isSelected()) {
            reporte_paciente reporte = new reporte_paciente();
            reporte.reportePacientesPorFechas(fecha_inicial, fecha_final);
            
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dcofecha_finalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcofecha_finalPropertyChange
        // TODO add your handling code here:
        Formatter fmt = new Formatter();
        try {
            int f_dia = dcofecha_final.getCalendar().get(Calendar.DAY_OF_MONTH);
            
            int f_mes = dcofecha_final.getCalendar().get(Calendar.MONTH) + 1;
            String mes = null;
            int Agosto = 8;
            int Septiembre = 9;
            if (f_mes == 01) {
                mes = "01";
            } else if (f_mes == 02) {
                mes = "02";
            } else if (f_mes == 03) {
                mes = "03";
            } else if (f_mes == 04) {
                mes = "04";
            } else if (f_mes == 05) {
                mes = "05";
            } else if (f_mes == 06) {
                mes = "06";
            } else if (f_mes == 07) {
                mes = "07";
            } else if (f_mes == Agosto) {
                mes = "08";
            } else if (f_mes == Septiembre) {
                mes = "09";
            } else if (f_mes == 10) {
                mes = "10";
            } else if (f_mes == 11) {
                mes = "11";
            } else if (f_mes == 12) {
                mes = "12";
            }
            int f_año = dcofecha_final.getCalendar().get(Calendar.YEAR);
            
            lblfecha_final.setText(f_año + "-" + mes + "-" + fmt.format("%02d", f_dia));
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_dcofecha_finalPropertyChange

    private void dcofecha_inicialPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcofecha_inicialPropertyChange
//         TODO add your handling code here:
        Formatter fmt = new Formatter();
        try {
            int f_dia = dcofecha_inicial.getCalendar().get(Calendar.DAY_OF_MONTH);
            int f_mes = dcofecha_inicial.getCalendar().get(Calendar.MONTH) + 1;
            String mes = null;
            int Agosto = 8;
            int Septiembre = 9;
            if (f_mes == 01) {
                mes = "01";
            } else if (f_mes == 02) {
                mes = "02";
            } else if (f_mes == 03) {
                mes = "03";
            } else if (f_mes == 04) {
                mes = "04";
            } else if (f_mes == 05) {
                mes = "05";
            } else if (f_mes == 06) {
                mes = "06";
            } else if (f_mes == 07) {
                mes = "07";
            } else if (f_mes == Agosto) {
                mes = "08";
            } else if (f_mes == Septiembre) {
                mes = "09";
            } else if (f_mes == 10) {
                mes = "10";
            } else if (f_mes == 11) {
                mes = "11";
            } else if (f_mes == 12) {
                mes = "12";
            }
            int f_año = dcofecha_inicial.getCalendar().get(Calendar.YEAR);
            
            lblfecha_inicial.setText(f_año + "-" + mes + "-" + fmt.format("%02d", f_dia));
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_dcofecha_inicialPropertyChange

    private void rbtFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtFarmaciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcofecha_final;
    private com.toedter.calendar.JDateChooser dcofecha_inicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblfecha_final;
    private javax.swing.JLabel lblfecha_inicial;
    private javax.swing.JRadioButton rbtCaja;
    private javax.swing.JRadioButton rbtCertificadoSalud;
    private javax.swing.JRadioButton rbtFarmacia;
    private javax.swing.JRadioButton rbtInformeMedico;
    private javax.swing.JRadioButton rbtPaciente;
    private javax.swing.ButtonGroup rbtReportes;
    // End of variables declaration//GEN-END:variables

    private static java.sql.Date converUtilToSql(java.util.Date Fecha_I) {
        java.sql.Date sqlDate = new java.sql.Date(Fecha_I.getTime());
        return sqlDate;
    }
    
    private static java.sql.Date converUtilToSqlII(java.util.Date Fecha_F) {
        java.sql.Date sqlDateII = new java.sql.Date(Fecha_F.getTime());
        return sqlDateII;
    }
    
}
